kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: helloworld
spec:
  tasks:
    - name: task-1
      taskSpec:
        steps:
          - image: quay.io/fedora/fedora:38
            name: hello
            script: |
              echo "hello world!"
